import Head from "next/head";
import { GetStaticProps } from "next";
import { getBlogList } from "@/service";
import fs from "fs";
import matter from "gray-matter";
import MarkdownRender from "@/components/MarkdownRender";
import { projectList } from "@/constant";
import Link from "next/link";

interface ProjectProps {
  title: string;
  date: string;
  tag: string[];
  excerpt: string;
  content: string;
}

export default function Project({
  title,
  date,
  tag,
  excerpt,
  content,
}: ProjectProps) {
  console.log(content);
  return (
    <>
      <Head>
        <title>WayneChoi.dev || Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      {projectList.map((project) => (
        <Link key={project.slug} href={`project/${project.slug}`}>
          {project.subject}
        </Link>
      ))}
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const response = await fetch(
    "https://waynechoidev.github.io/turing-machine/README.md"
  );
  const markdownWithMeta = await response.text();

  console.log(markdownWithMeta);
  const { content } = matter(markdownWithMeta);
  return {
    props: { content },
  };
};
