import Head from "next/head";
import { GetStaticProps } from "next";
import { getBlogList } from "@/service";

interface BlogProps {
  posts: {
    slug: string;
    title: string;
    date: string;
    tag: string[];
    excerpt: string;
    content: string;
  }[];
}

export default function Blog({ posts }: BlogProps) {
  return (
    <>
      <Head>
        <title>WayneChoi.dev || Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      {posts.map((post, index) => (
        <a href={`blog/${post.slug}`} key={index}>
          <p>{post.title}</p>
        </a>
      ))}
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const posts = getBlogList();
  return {
    props: {
      posts,
    },
  };
};
