import Head from "next/head";
import Typography from "@mui/material/Typography";
import { GetStaticProps } from "next";
import { getBlogList } from "@/service";

export default function Home() {
  return (
    <>
      <Head>
        <title>WayneChoi.dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <p>It is still on progress...</p>
    </>
  );
}
