import Head from "next/head";
import Typography from "@mui/material/Typography";
import { GetStaticProps } from "next";
import { getBlogList } from "@/service";

interface HomeProps {
  posts: {
    slug: string;
    title: string;
    date: string;
    tag: string[];
    excerpt: string;
    content: string;
  }[];
}

export default function Home({ posts }: HomeProps) {
  return (
    <>
      <Head>
        <title>WayneChoi.dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={`favicon.ico`} />
      </Head>
      <Typography variant="h1" gutterBottom>
        Blog
      </Typography>
      <main className="text-3xl font-bold underline">Hello world</main>
      {posts.map((post, index) => (
        <a href={post.slug} key={index}>
          <p>{post.title}</p>
        </a>
      ))}
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const posts = getBlogList();
  return {
    props: {
      posts,
    },
  };
};
