import Head from "next/head";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";

export default function Home() {
  return (
    <>
      <Head>
        <title>WayneChoi.dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={`favicon.ico`} />
      </Head>
      <Typography variant="h1" gutterBottom>
        Blog
      </Typography>
      <main className="text-3xl font-bold underline">Hello world</main>
    </>
  );
}
